# server
server:
  localhost_ip: 127.0.0.1
  ip: 0.0.0.0
  port: 80
  secret: yuan_cheng_second_kill

# mysql
mysql:
  user: root
  password: yc980704
  ip: 121.41.59.142
  port: 3306
  db_name: seckill

# redis
redis:
  ip: 121.41.59.142
  port: 6379
  password: yc980704
  DB: 0

# rabbitmq
rabbitMQ:
  ip: 121.41.59.142
  port: 5672
  user: yuancheng
  password: yc980704
  exchange: seckill # 交换机名称
  exchangeType: direct # 交换机类型
  queue: seckill # 队列名称
  routingKey: seckill # 路由(绑定到哪个queue)
  continuous: false  # 是否恒定速率

# consistent hash
ringHash:
  ips:
    - 127.0.0.1
    - 121.41.59.142
  replicas: 3
