# server
server:
  localhost_ip: 127.0.0.1
  ip: 0.0.0.0
  port: 80
  secret: yuan_cheng_second_kill

# mysql
mysql:
  user: root
  password: yc980704
  ip: 121.41.59.142
  port: 3306
  db_name: seckill

# redis
redis:
  ip: 121.41.59.142
  port: 6379
  password: yc980704
  DB: 0

# rabbitmq
rabbitMQ:
  ip: 121.41.59.142
  port: 5672
  user: yuancheng
  password: yc980704
  name: seckill # 队列名称

# consistent hash
ringHash:
  ips:
    - 127.0.0.1
    - 121.41.59.142
  replicas: 3
